# ชื่อของ Workflow
name: Deploy DBS Project to GitHub Pages (Simple)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # ---- ส่วนที่เปลี่ยนแปลง ----
      # ไม่ใช้ Jekyll แต่สร้างโฟลเดอร์สำหรับ deploy โดยตรง
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Create Site Folder
        run: mkdir -p ./_site && cp -r ./* ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      # ---- จบส่วนที่เปลี่ยนแปลง ----

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
